// 街机游戏英文名映射表
const arcadeNameMap = {
  '魂斗罗': 'Contra',
  '雪人兄弟': 'Snow Bros',
  '龙行忍者': 'Ninja Spirit',
  '1941反击战': '1941: Counter Attack',
  '1942空中大战': '1942',
  '1943-中途岛海战': '1943: The Battle of Midway',
  '19XX命运否决战': '19XX: The War Against Destiny',
  'Blood Bros': 'Blood Bros',
  '月影战士': 'Moon Shadow Warrior',
  '星宿战士': 'Star Soldier',
  'Q版沙罗曼蛇': 'Parodius',
  'SPY间谍猎人': 'Spy Hunter',
  '兵蜂': 'TwinBee',
  '原始岛': 'Prehistoric Isle',
  '双截龙': 'Double Dragon',
  '变形战斗机': 'Transformers',
  '古巴战士': 'Guerrilla War',
  '吞食鱼': 'Feeding Frenzy',
  '吞食天地2赤壁之战': 'Warriors of Fate',
  '圆桌骑士': 'Knights of the Round',
  '地狱门': 'Hellfire',
  '快打旋风': 'Final Fight',
  '怒': 'Ikari Warriors',
  '恐龙快打': 'Cadillacs and Dinosaurs',
  '惩罚者/复仇者': 'The Punisher',
  '战国之刃': 'Samurai Aces',
  '战国原始岛': 'Samurai Prehistoric Isle',
  '战机': 'Airplane',
  '捉虫敢死队': 'Exterminator',
  '捉鬼大师': 'Ghost Hunter',
  '摔角霸王': 'Saturday Night Slam Masters',
  '新恐龙快打': 'New Cadillacs and Dinosaurs',
  '沙罗曼蛇': 'Salamander',
  '海底大战争': 'In The Hunt',
  '西游释厄传': 'Oriental Legend',
  '深渊魔域': 'Abyss',
  '绿色兵团': 'Rush\'n Attack',
  '绿色兵团2': 'Green Beret 2',
  '群殴': 'Gang Wars',
  '联合大作战': 'Joint Strike',
  '脱狱-战俘': 'P.O.W.',
  '花式撞球': 'Side Pocket',
  '落日骑士': 'Sunset Riders',
  '街头霸王': 'Street Fighter',
  '街头霸王2四大天王': 'Street Fighter II',
  '街头霸王2-16人版': 'Street Fighter II Champion Edition',
  '西游释厄录': 'Oriental Legend',
  '热血新一军': 'Nekketsu',
  '雷电': 'Raiden',
  '雷电2': 'Raiden II',
  '雷电3': 'Raiden III',
  '雷电4': 'Raiden IV',
  '雷电5': 'Raiden V',
  '合金弹头': 'Metal Slug',
  '合金弹头2': 'Metal Slug 2',
  '合金弹头3': 'Metal Slug 3',
  '合金弹头4': 'Metal Slug 4',
  '合金弹头5': 'Metal Slug 5',
  '合金弹头6': 'Metal Slug 6',
  '合金弹头7': 'Metal Slug 7',
  '合金弹头8': 'Metal Slug 8',
  '合金弹头9': 'Metal Slug 9',
  '合金弹头X': 'Metal Slug X',
  '拳皇94': 'The King of Fighters \'94',
  '拳皇95': 'The King of Fighters \'95',
  '拳皇96': 'The King of Fighters \'96',
  '拳皇97': 'The King of Fighters \'97',
  '拳皇98': 'The King of Fighters \'98',
  '拳皇99': 'The King of Fighters \'99',
  '拳皇2000': 'The King of Fighters 2000',
  '拳皇2001': 'The King of Fighters 2001',
  '拳皇2002': 'The King of Fighters 2002',
  '拳皇2003': 'The King of Fighters 2003',
  '侍魂': 'Samurai Shodown',
  '侍魂2': 'Samurai Shodown II',
  '侍魂3': 'Samurai Shodown III',
  '侍魂4': 'Samurai Shodown IV',
  '侍魂5': 'Samurai Shodown V',
  '饿狼传说': 'Fatal Fury',
  '饿狼传说2': 'Fatal Fury 2',
  '饿狼传说3': 'Fatal Fury 3',
  '饿狼传说特别版': 'Fatal Fury Special',
  '月华剑士': 'The Last Blade',
  '月华剑士2': 'The Last Blade 2',
  '世界英雄': 'World Heroes',
  '世界英雄2': 'World Heroes 2',
  '世界英雄完美版': 'World Heroes Perfect',
  '风云默示录': 'Savage Reign',
  '风云默示录2': 'Kizuna Encounter',
  '龙虎之拳': 'Art of Fighting',
  '龙虎之拳2': 'Art of Fighting 2',
  '龙虎之拳3': 'Art of Fighting 3',
  '超能力战士': 'Psycho Soldier',
  '雅典娜': 'Athena',
  '怒之铁拳': 'Streets of Rage',
  '怒之铁拳2': 'Streets of Rage 2',
  '怒之铁拳3': 'Streets of Rage 3',
  '战斧': 'Golden Axe',
  '战斧2': 'Golden Axe II',
  '战斧3': 'Golden Axe III',
  '兽王记': 'Altered Beast',
  '兽王记2': 'Altered Beast II',
  '兽王记3': 'Altered Beast III',
  '神奇男孩': 'Wonder Boy',
  '神奇男孩2': 'Wonder Boy II',
  '神奇男孩3': 'Wonder Boy III',
  '冒险岛': 'Adventure Island',
  '冒险岛2': 'Adventure Island II',
  '冒险岛3': 'Adventure Island III',
  '冒险岛4': 'Adventure Island IV',
  '超级玛丽': 'Super Mario Bros',
  '超级玛丽2': 'Super Mario Bros 2',
  '超级玛丽3': 'Super Mario Bros 3',
  '魂斗罗2': 'Super Contra',
  '魂斗罗3': 'Contra III',
  '魂斗罗4': 'Contra IV',
  '魂斗罗力量': 'Contra Force',
  '赤色要塞': 'Jackal',
  '绿色兵团': 'Rush\'n Attack',
  '沙罗曼蛇': 'Salamander',
  '宇宙巡航机': 'Gradius',
  '宇宙巡航机2': 'Gradius II',
  '宇宙巡航机3': 'Gradius III',
  '宇宙巡航机4': 'Gradius IV',
  '宇宙巡航机5': 'Gradius V',
  '雷电': 'Raiden',
  '雷电2': 'Raiden II',
  '雷电3': 'Raiden III',
  '雷电4': 'Raiden IV',
  '雷电5': 'Raiden V',
  '打击者1945': 'Strikers 1945',
  '打击者1945 II': 'Strikers 1945 II',
  '打击者1945 III': 'Strikers 1945 III',
  '四国战机': 'Sonic Wings',
  '四国战机2': 'Sonic Wings 2',
  '四国战机3': 'Sonic Wings 3',
  '雌虎战机': 'Tiger Heli',
  '雌虎战机2': 'Tiger Heli 2',
  '鲛鲛鲛': 'Flying Shark',
  '鲛鲛鲛2': 'Flying Shark 2',
  '捉虫敢死队': 'Exterminator',
  '捉鬼大师': 'Ghost Hunter',
  '地狱门': 'Hellfire',
  '地狱门2': 'Hellfire 2',
  '地狱门3': 'Hellfire 3',
  '海底大战争': 'In The Hunt',
  '海底大战争2': 'In The Hunt 2',
  '合金弹头': 'Metal Slug',
  '合金弹头2': 'Metal Slug 2',
  '合金弹头3': 'Metal Slug 3',
  '合金弹头4': 'Metal Slug 4',
  '合金弹头5': 'Metal Slug 5',
  '合金弹头6': 'Metal Slug 6',
  '合金弹头7': 'Metal Slug 7',
  '合金弹头8': 'Metal Slug 8',
  '合金弹头9': 'Metal Slug 9',
  '合金弹头X': 'Metal Slug X',
  '突击奇兵': 'Shock Troopers',
  '突击奇兵2': 'Shock Troopers 2',
  '敌后奇兵': 'Commando',
  '敌后奇兵2': 'Commando 2',
  '敌后奇兵3': 'Commando 3',
  '战场之狼': 'Commando',
  '战场之狼2': 'Commando 2',
  '战场之狼3': 'Commando 3',
  '古巴战士': 'Guerrilla War',
  '古巴战士2': 'Guerrilla War 2',
  '双截龙': 'Double Dragon',
  '双截龙2': 'Double Dragon II',
  '双截龙3': 'Double Dragon III',
  '双截龙4': 'Double Dragon IV',
  '快打旋风': 'Final Fight',
  '快打旋风2': 'Final Fight 2',
  '快打旋风3': 'Final Fight 3',
  '街头霸王': 'Street Fighter',
  '街头霸王2': 'Street Fighter II',
  '街头霸王3': 'Street Fighter III',
  '街头霸王4': 'Street Fighter IV',
  '街头霸王5': 'Street Fighter V',
  '少年街霸': 'Street Fighter Alpha',
  '少年街霸2': 'Street Fighter Alpha 2',
  '少年街霸3': 'Street Fighter Alpha 3',
  '拳皇': 'The King of Fighters',
  '拳皇94': 'The King of Fighters \'94',
  '拳皇95': 'The King of Fighters \'95',
  '拳皇96': 'The King of Fighters \'96',
  '拳皇97': 'The King of Fighters \'97',
  '拳皇98': 'The King of Fighters \'98',
  '拳皇99': 'The King of Fighters \'99',
  '拳皇2000': 'The King of Fighters 2000',
  '拳皇2001': 'The King of Fighters 2001',
  '拳皇2002': 'The King of Fighters 2002',
  '拳皇2003': 'The King of Fighters 2003',
  '侍魂': 'Samurai Shodown',
  '侍魂2': 'Samurai Shodown II',
  '侍魂3': 'Samurai Shodown III',
  '侍魂4': 'Samurai Shodown IV',
  '侍魂5': 'Samurai Shodown V',
  '饿狼传说': 'Fatal Fury',
  '饿狼传说2': 'Fatal Fury 2',
  '饿狼传说3': 'Fatal Fury 3',
  '饿狼传说特别版': 'Fatal Fury Special',
  '月华剑士': 'The Last Blade',
  '月华剑士2': 'The Last Blade 2',
  '世界英雄': 'World Heroes',
  '世界英雄2': 'World Heroes 2',
  '世界英雄完美版': 'World Heroes Perfect',
  '风云默示录': 'Savage Reign',
  '风云默示录2': 'Kizuna Encounter',
  '龙虎之拳': 'Art of Fighting',
  '龙虎之拳2': 'Art of Fighting 2',
  '龙虎之拳3': 'Art of Fighting 3',
  '超能力战士': 'Psycho Soldier',
  '雅典娜': 'Athena',
  '怒之铁拳': 'Streets of Rage',
  '怒之铁拳2': 'Streets of Rage 2',
  '怒之铁拳3': 'Streets of Rage 3',
  '战斧': 'Golden Axe',
  '战斧2': 'Golden Axe II',
  '战斧3': 'Golden Axe III',
  '兽王记': 'Altered Beast',
  '兽王记2': 'Altered Beast II',
  '兽王记3': 'Altered Beast III',
  '神奇男孩': 'Wonder Boy',
  '神奇男孩2': 'Wonder Boy II',
  '神奇男孩3': 'Wonder Boy III',
  '冒险岛': 'Adventure Island',
  '冒险岛2': 'Adventure Island II',
  '冒险岛3': 'Adventure Island III',
  '冒险岛4': 'Adventure Island IV',
  '超级玛丽': 'Super Mario Bros',
  '超级玛丽2': 'Super Mario Bros 2',
  '超级玛丽3': 'Super Mario Bros 3',
  '魂斗罗2': 'Super Contra',
  '魂斗罗3': 'Contra III',
  '魂斗罗4': 'Contra IV',
  '魂斗罗力量': 'Contra Force',
  '赤色要塞': 'Jackal',
  '绿色兵团': 'Rush\'n Attack',
  '沙罗曼蛇': 'Salamander',
  '宇宙巡航机': 'Gradius',
  '宇宙巡航机2': 'Gradius II',
  '宇宙巡航机3': 'Gradius III',
  '宇宙巡航机4': 'Gradius IV',
  '宇宙巡航机5': 'Gradius V',
  '雷电': 'Raiden',
  '雷电2': 'Raiden II',
  '雷电3': 'Raiden III',
  '雷电4': 'Raiden IV',
  '雷电5': 'Raiden V',
  '打击者1945': 'Strikers 1945',
  '打击者1945 II': 'Strikers 1945 II',
  '打击者1945 III': 'Strikers 1945 III',
  '四国战机': 'Sonic Wings',
  '四国战机2': 'Sonic Wings 2',
  '四国战机3': 'Sonic Wings 3',
  '雌虎战机': 'Tiger Heli',
  '雌虎战机2': 'Tiger Heli 2',
  '鲛鲛鲛': 'Flying Shark',
  '鲛鲛鲛2': 'Flying Shark 2',
  '捉虫敢死队': 'Exterminator',
  '捉鬼大师': 'Ghost Hunter',
  '地狱门': 'Hellfire',
  '地狱门2': 'Hellfire 2',
  '地狱门3': 'Hellfire 3',
  '海底大战争': 'In The Hunt',
  '海底大战争2': 'In The Hunt 2',
  '合金弹头': 'Metal Slug',
  '合金弹头2': 'Metal Slug 2',
  '合金弹头3': 'Metal Slug 3',
  '合金弹头4': 'Metal Slug 4',
  '合金弹头5': 'Metal Slug 5',
  '合金弹头6': 'Metal Slug 6',
  '合金弹头7': 'Metal Slug 7',
  '合金弹头8': 'Metal Slug 8',
  '合金弹头9': 'Metal Slug 9',
  '合金弹头X': 'Metal Slug X',
  '突击奇兵': 'Shock Troopers',
  '突击奇兵2': 'Shock Troopers 2',
  '敌后奇兵': 'Commando',
  '敌后奇兵2': 'Commando 2',
  '敌后奇兵3': 'Commando 3',
  '战场之狼': 'Commando',
  '战场之狼2': 'Commando 2',
  '战场之狼3': 'Commando 3',
  '古巴战士': 'Guerrilla War',
  '古巴战士2': 'Guerrilla War 2',
  '双截龙': 'Double Dragon',
  '双截龙2': 'Double Dragon II',
  '双截龙3': 'Double Dragon III',
  '双截龙4': 'Double Dragon IV',
  '快打旋风': 'Final Fight',
  '快打旋风2': 'Final Fight 2',
  '快打旋风3': 'Final Fight 3',
  '街头霸王': 'Street Fighter',
  '街头霸王2': 'Street Fighter II',
  '街头霸王3': 'Street Fighter III',
  '街头霸王4': 'Street Fighter IV',
  '街头霸王5': 'Street Fighter V',
  '少年街霸': 'Street Fighter Alpha',
  '少年街霸2': 'Street Fighter Alpha 2',
  '少年街霸3': 'Street Fighter Alpha 3',
  '圆桌骑士': 'Knights of the Round',
  '三国志': 'Warriors of Fate',
  '三国志2': 'Warriors of Fate 2',
  '吞食天地': 'Dynasty Wars',
  '吞食天地2': 'Warriors of Fate',
  '龙王': 'The King of Dragons',
  '龙王战士': 'The King of Dragons',
  '魔法剑': 'Magic Sword',
  '魔法剑英雄幻想': 'Magic Sword',
  '名将': 'Captain Commando',
  '恐龙快打': 'Cadillacs and Dinosaurs',
  '恐龙新世纪': 'Cadillacs and Dinosaurs',
  '惩罚者': 'The Punisher',
  '复仇者': 'The Punisher',
  '异形': 'Aliens',
  '异形大战铁血战士': 'Alien vs Predator',
  '铁血战士': 'Predator',
  '超级魂斗罗': 'Super Contra',
  '魂斗罗归来': 'Contra Returns',
  '魂斗罗进化革命': 'Contra Evolution',
  '魂斗罗铁血军团': 'Contra: Hard Corps',
  '魂斗罗重生': 'Contra ReBirth',
  '魂斗罗4': 'Contra 4',
  '魂斗罗双雄战魂': 'Contra: Rogue Corps',
  '魂斗罗RC联盟': 'Contra: Rogue Corps',
  '魂斗罗无赖军团': 'Contra: Rogue Corps',
  '魂斗罗加鲁加行动': 'Contra: Operation Galuga',
  '超级魂斗罗2': 'Super C',
  '魂斗罗精神': 'Contra III: The Alien Wars',
  '魂斗罗3异型战争': 'Contra III: The Alien Wars',
  '魂斗罗力量': 'Contra Force',
  '魂斗罗冒险': 'Contra: The Alien Wars',
  '魂斗罗铁血兵团': 'Contra: Hard Corps',
  '魂斗罗战争遗产': 'Contra: Legacy of War',
  '魂斗罗冒险岛': 'Contra: The Alien Wars',
  '魂斗罗进化': 'Contra Evolution',
  '魂斗罗归来': 'Contra Returns',
  '魂斗罗重制版': 'Contra Remake',
  '魂斗罗周年纪念版': 'Contra Anniversary Collection',
  '魂斗罗合集': 'Contra Anniversary Collection',
  '魂斗罗30条命': 'Contra 30 Lives',
  '魂斗罗无敌版': 'Contra Invincible',
  '魂斗罗无限命': 'Contra Infinite Lives',
  '魂斗罗改版': 'Contra Hack',
  '魂斗罗魔改版': 'Contra Hack',
  '魂斗罗变态版': 'Contra Hard Mode',
  '魂斗罗困难版': 'Contra Hard Mode',
  '魂斗罗加强版': 'Contra Plus',
  '魂斗罗增强版': 'Contra Plus',
  '魂斗罗完美版': 'Contra Perfect',
  '魂斗罗终极版': 'Contra Ultimate',
  '魂斗罗黄金版': 'Contra Gold',
  '魂斗罗白金版': 'Contra Platinum',
  '魂斗罗钻石版': 'Contra Diamond',
  '魂斗罗珍藏版': 'Contra Collection',
  '魂斗罗纪念版': 'Contra Memorial',
  '魂斗罗经典版': 'Contra Classic',
  '魂斗罗原版': 'Contra Original',
  '魂斗罗初代': 'Contra Original',
  '魂斗罗1代': 'Contra',
  '魂斗罗2代': 'Super Contra',
  '魂斗罗3代': 'Contra III',
  '魂斗罗4代': 'Contra 4',
  '魂斗罗5代': 'Contra 5',
  '魂斗罗6代': 'Contra 6',
  '魂斗罗7代': 'Contra 7',
  '魂斗罗8代': 'Contra 8',
  '魂斗罗9代': 'Contra 9',
  '魂斗罗10代': 'Contra 10',
  '魂斗罗X代': 'Contra X',
  '魂斗罗S代': 'Contra S',
  '魂斗罗M代': 'Contra M',
  '魂斗罗L代': 'Contra L',
  '魂斗罗R代': 'Contra R',
  '魂斗罗Z代': 'Contra Z',
  '魂斗罗ZERO': 'Contra Zero',
  '魂斗罗EX': 'Contra EX',
  '魂斗罗DX': 'Contra DX',
  '魂斗罗GX': 'Contra GX',
  '魂斗罗FX': 'Contra FX',
  '魂斗罗MX': 'Contra MX',
  '魂斗罗NX': 'Contra NX',
  '魂斗罗PX': 'Contra PX',
  '魂斗罗QX': 'Contra QX',
  '魂斗罗RX': 'Contra RX',
  '魂斗罗SX': 'Contra SX',
  '魂斗罗TX': 'Contra TX',
  '魂斗罗UX': 'Contra UX',
  '魂斗罗VX': 'Contra VX',
  '魂斗罗WX': 'Contra WX',
  '魂斗罗XX': 'Contra XX',
  '魂斗罗YX': 'Contra YX',
  '魂斗罗ZX': 'Contra ZX',
  '雪人兄弟2': 'Snow Bros 2',
  '雪人兄弟3': 'Snow Bros 3',
  '雪人兄弟特别版': 'Snow Bros Special',
  '雪人兄弟无敌版': 'Snow Bros Invincible',
  '雪人兄弟无限命': 'Snow Bros Infinite Lives',
  '雪人兄弟改版': 'Snow Bros Hack',
  '雪人兄弟魔改版': 'Snow Bros Hack',
  '雪人兄弟变态版': 'Snow Bros Hard Mode',
  '雪人兄弟困难版': 'Snow Bros Hard Mode',
  '雪人兄弟加强版': 'Snow Bros Plus',
  '雪人兄弟增强版': 'Snow Bros Plus',
  '雪人兄弟完美版': 'Snow Bros Perfect',
  '雪人兄弟终极版': 'Snow Bros Ultimate',
  '雪人兄弟黄金版': 'Snow Bros Gold',
  '雪人兄弟白金版': 'Snow Bros Platinum',
  '雪人兄弟钻石版': 'Snow Bros Diamond',
  '雪人兄弟珍藏版': 'Snow Bros Collection',
  '雪人兄弟纪念版': 'Snow Bros Memorial',
  '雪人兄弟经典版': 'Snow Bros Classic',
  '雪人兄弟原版': 'Snow Bros Original',
  '雪人兄弟初代': 'Snow Bros Original',
  '雪人兄弟1代': 'Snow Bros',
  '雪人兄弟2代': 'Snow Bros 2',
  '雪人兄弟3代': 'Snow Bros 3',
  '雪人兄弟4代': 'Snow Bros 4',
  '雪人兄弟5代': 'Snow Bros 5',
  '雪人兄弟X代': 'Snow Bros X',
  '雪人兄弟S代': 'Snow Bros S',
  '雪人兄弟M代': 'Snow Bros M',
  '雪人兄弟L代': 'Snow Bros L',
  '雪人兄弟R代': 'Snow Bros R',
  '雪人兄弟Z代': 'Snow Bros Z',
  '雪人兄弟ZERO': 'Snow Bros Zero',
  '雪人兄弟EX': 'Snow Bros EX',
  '雪人兄弟DX': 'Snow Bros DX',
  '雪人兄弟GX': 'Snow Bros GX',
  '雪人兄弟FX': 'Snow Bros FX',
  '雪人兄弟MX': 'Snow Bros MX',
  '雪人兄弟NX': 'Snow Bros NX',
  '雪人兄弟PX': 'Snow Bros PX',
  '雪人兄弟QX': 'Snow Bros QX',
  '雪人兄弟RX': 'Snow Bros RX',
  '雪人兄弟SX': 'Snow Bros SX',
  '雪人兄弟TX': 'Snow Bros TX',
  '雪人兄弟UX': 'Snow Bros UX',
  '雪人兄弟VX': 'Snow Bros VX',
  '雪人兄弟WX': 'Snow Bros WX',
  '雪人兄弟XX': 'Snow Bros XX',
  '雪人兄弟YX': 'Snow Bros YX',
  '雪人兄弟ZX': 'Snow Bros ZX',
  '龙行忍者2': 'Ninja Spirit 2',
  '龙行忍者3': 'Ninja Spirit 3',
  '龙行忍者特别版': 'Ninja Spirit Special',
  '龙行忍者无敌版': 'Ninja Spirit Invincible',
  '龙行忍者无限命': 'Ninja Spirit Infinite Lives',
  '龙行忍者改版': 'Ninja Spirit Hack',
  '龙行忍者魔改版': 'Ninja Spirit Hack',
  '龙行忍者变态版': 'Ninja Spirit Hard Mode',
  '龙行忍者困难版': 'Ninja Spirit Hard Mode',
  '龙行忍者加强版': 'Ninja Spirit Plus',
  '龙行忍者增强版': 'Ninja Spirit Plus',
  '龙行忍者完美版': 'Ninja Spirit Perfect',
  '龙行忍者终极版': 'Ninja Spirit Ultimate',
  '龙行忍者黄金版': 'Ninja Spirit Gold',
  '龙行忍者白金版': 'Ninja Spirit Platinum',
  '龙行忍者钻石版': 'Ninja Spirit Diamond',
  '龙行忍者珍藏版': 'Ninja Spirit Collection',
  '龙行忍者纪念版': 'Ninja Spirit Memorial',
  '龙行忍者经典版': 'Ninja Spirit Classic',
  '龙行忍者原版': 'Ninja Spirit Original',
  '龙行忍者初代': 'Ninja Spirit Original',
  '龙行忍者1代': 'Ninja Spirit',
  '龙行忍者2代': 'Ninja Spirit 2',
  '龙行忍者3代': 'Ninja Spirit 3',
  '龙行忍者4代': 'Ninja Spirit 4',
  '龙行忍者5代': 'Ninja Spirit 5',
  '龙行忍者X代': 'Ninja Spirit X',
  '龙行忍者S代': 'Ninja Spirit S',
  '龙行忍者M代': 'Ninja Spirit M',
  '龙行忍者L代': 'Ninja Spirit L',
  '龙行忍者R代': 'Ninja Spirit R',
  '龙行忍者Z代': 'Ninja Spirit Z',
  '龙行忍者ZERO': 'Ninja Spirit Zero',
  '龙行忍者EX': 'Ninja Spirit EX',
  '龙行忍者DX': 'Ninja Spirit DX',
  '龙行忍者GX': 'Ninja Spirit GX',
  '龙行忍者FX': 'Ninja Spirit FX',
  '龙行忍者MX': 'Ninja Spirit MX',
  '龙行忍者NX': 'Ninja Spirit NX',
  '龙行忍者PX': 'Ninja Spirit PX',
  '龙行忍者QX': 'Ninja Spirit QX',
  '龙行忍者RX': 'Ninja Spirit RX',
  '龙行忍者SX': 'Ninja Spirit SX',
  '龙行忍者TX': 'Ninja Spirit TX',
  '龙行忍者UX': 'Ninja Spirit UX',
  '龙行忍者VX': 'Ninja Spirit VX',
  '龙行忍者WX': 'Ninja Spirit WX',
  '龙行忍者XX': 'Ninja Spirit XX',
  '龙行忍者YX': 'Ninja Spirit YX',
  '龙行忍者ZX': 'Ninja Spirit ZX',
};

module.exports = { arcadeNameMap };
